apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  Namespace: cicd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: betrand1997/cicd-image
          image: betrand1997/cicd-image:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Never