apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: cicd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: cicd-image  # ✅ Updated container name (Valid RFC 1123 format)
          image: betrand1997/cicd-image:latest  # ✅ Keep this as it is
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
