apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
  namespace: cicd-namespace
spec:
  type: NodePort
  selector:
    app: hello-world-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007