name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ##################### Build ################
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: betrand1997/docker-workflow-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Clean Dist Directory
        run: |
          rm -rf build dist *.egg-info

      - name: Build Package
        run: |
          source venv/bin/activate
          pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
          ls dist

  ##################### Unit-Test ################
  test:
    name: Unit-Test
    runs-on: ubuntu-latest
    needs: build
    container:
      image: betrand1997/docker-workflow-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python and Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          pip install pytest
          pytest test_app.py

  ##################### SonarQube Scan ################
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  ##################### Publish to PyPI ################
  package-and-publish:
    name: Package and Publish to PyPI
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies for Packaging
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      - name: Bump Version
        run: |
          source venv/bin/activate
          bump2version patch  # Use 'minor' or 'major' as appropriate

      - name: Build Package Again
        run: |
          source venv/bin/activate
          python setup.py sdist bdist_wheel
          ls dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source venv/bin/activate
          twine upload dist/*

  ##################### Deploy to EC2 ################
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: package-and-publish

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@3.235.142.37 bash << EOF
            # Update package lists
            sudo apt-get update -y

            # Install necessary system packages
            sudo apt-get install -y python3-pip python3-venv

            # Navigate to the project directory
            cd /home/ubuntu/cicd/

            # Create virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Activate the virtual environment
            source venv/bin/activate

            # Upgrade pip and install the latest package
            pip install --upgrade pip setuptools wheel
            pip install --upgrade betrand-ngoh-mutagha-version

            # Verify Flask installation
            pip show flask || pip install flask

            # Restart the Flask application using systemd
            sudo systemctl daemon-reload
            sudo systemctl restart flask_app
          EOF

          # Clean up the private key file
          rm ec2_key.pem

      - name: Output Application URL
        if: success()
        run: echo "Application is accessible at http://3.235.142.37:8000"
